In [1]:
import pandas as pd
import numpy as np

customers=pd.read_csv(r"C:\Users\admin\Desktop\Data Analysis Projects\Behavioral Economics Project\customers.csv")
products=pd.read_csv(r"C:\Users\admin\Desktop\Data Analysis Projects\Behavioral Economics Project\products.csv")
transactions=pd.read_csv(r"C:\Users\admin\Desktop\Data Analysis Projects\Behavioral Economics Project\transactions.csv")

In [2]:
customers.shape #rows and columns of the dataset

(1500, 9)

In [3]:
customers.columns #columns of the dataset

Index(['CustomerID', 'Age', 'Gender', 'City', 'IncomeLevel', 'Occupation',
       'LoyaltyMember', 'YearsAsCustomer', 'BrandFamiliarity'],
      dtype='object')

In [4]:
customers.describe() #summary statistics of the dataset

        CustomerID          Age  YearsAsCustomer
count  1500.000000  1500.000000      1500.000000
mean    750.500000    41.681333         2.392667
std     433.157015    13.781330         3.316898
min       1.000000    18.000000         0.000000
25%     375.750000    29.000000         0.000000
50%     750.500000    42.000000         0.000000
75%    1125.250000    54.000000         5.000000
max    1500.000000    65.000000        10.000000

In [5]:
customers.info() #summary of datatypes of the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        1500 non-null   int64
 1   Age               1500 non-null   int64
 2   Gender            1500 non-null   object
 3   City              1500 non-null   object
 4   IncomeLevel       1500 non-null   object
 5   Occupation        1500 non-null   object
 6   LoyaltyMember     1500 non-null   object
 7   YearsAsCustomer   1500 non-null   int64
 8   BrandFamiliarity  1500 non-null   object
dtypes: int64(3), object(6)
memory usage: 105.6+ KB

In [6]:
customers.isnull().sum() #checking for nulls

CustomerID          0
Age                 0
Gender              0
City                0
IncomeLevel         0
Occupation          0
LoyaltyMember       0
YearsAsCustomer     0
BrandFamiliarity    0
dtype: int64

In [7]:
customers.duplicated().sum() #checking for duplicates

np.int64(0)

In [8]:
products.head()

,ProductID,Category,Brand,OriginalPrice,CurrentPrice,Rating,ReviewCount
0,1,Electronics,Sony,18446,11067.60,4.5,2251
1,2,Electronics,Dell,15156,13640.40,4.6,5241
2,3,Electronics,Sony,17501,16625.95,4.2,2078
3,4,Electronics,Samsung,44175,35340.00,4.9,3881
4,5,Electronics,Samsung,6789,5770.65,4.1,3476

In [9]:
products.shape #rows and columns of the dataset

(300, 7)

In [10]:
products.columns #columns of the dataset

Index(['ProductID', 'Category', 'Brand', 'OriginalPrice', 'CurrentPrice',
       'Rating', 'ReviewCount'],
      dtype='object')

In [11]:
products.describe() #summary statistics of the dataset

        ProductID  OriginalPrice  CurrentPrice      Rating  ReviewCount
count  300.000000     300.000000    300.000000  300.000000   300.000000
mean   150.500000   24987.350000  20296.043167    4.286667  2514.940000
std     86.746758   14089.871659  11741.071432    0.378726  1661.399262
min      1.000000     831.000000    561.600000    3.000000    20.000000
25%     75.750000   13306.750000  10513.175000    4.000000  1245.500000
50%    150.500000   24977.000000  20671.150000    4.300000  2396.000000
75%    225.250000   37053.750000  29460.625000    4.500000  3631.500000
max    300.000000   49982.000000  47164.650000    5.000000  9434.000000

In [12]:
products.info() #summary of datatypes of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductID      300 non-null    int64
 1   Category       300 non-null    object
 2   Brand          300 non-null    object
 3   OriginalPrice  300 non-null    int64
 4   CurrentPrice   300 non-null    float64
 5   Rating         300 non-null    float64
 6   ReviewCount    300 non-null    int64
dtypes: float64(2), int64(3), object(2)
memory usage: 16.5+ KB

In [13]:
products.isnull().sum() #checking for nulls

ProductID        0
Category         0
Brand            0
OriginalPrice    0
CurrentPrice     0
Rating           0
ReviewCount      0
dtype: int64

In [14]:
products.duplicated().sum() #checking for duplicates

np.int64(0)

In [15]:
transactions.head()

,TransactionID,CustomerID,ProductID,ScarcityMessage,CountdownTimer,RecommendedLabel,InfluencerCampaign,FreeShipping,TrendingBadge,Purchased,Quantity,FinalAmount,DecisionTimeMinutes
0,1,134,102,False,False,True,True,True,True,1,1,10565.9,22.49
1,2,1161,66,True,False,False,True,True,False,1,4,11775.6,8.64
2,3,982,157,False,True,False,True,True,True,0,0,0.0,13.07
3,4,659,199,True,False,True,False,False,False,0,0,0.0,15.29
4,5,650,79,True,False,False,False,False,False,0,0,0.0,23.14

In [16]:
transactions.shape #checking for rows and columns of the dataset

(10000, 13)

In [17]:
transactions.columns #columns of the datasets

Index(['TransactionID', 'CustomerID', 'ProductID', 'ScarcityMessage',
       'CountdownTimer', 'RecommendedLabel', 'InfluencerCampaign',
       'FreeShipping', 'TrendingBadge', 'Purchased', 'Quantity', 'FinalAmount',
       'DecisionTimeMinutes'],
      dtype='object')

In [18]:
transactions.describe() #summary statistics of the dataset

,TransactionID,CustomerID,ProductID,Purchased,Quantity,FinalAmount,DecisionTimeMinutes
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,745.062000,149.485100,0.689800,1.380100,27613.527230,13.420889
std,2886.89568,430.990381,86.726722,0.462598,1.284986,33737.363489,7.202244
min,1.00000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,2500.75000,371.000000,75.000000,0.000000,0.000000,0.000000,7.717500
50%,5000.50000,741.500000,150.000000,1.000000,1.000000,16854.550000,12.440000
75%,7500.25000,1119.000000,224.000000,1.000000,2.000000,40811.050000,19.000000
max,10000.00000,1500.000000,300.000000,1.000000,4.000000,188678.600000,47.040000

In [19]:
transactions.info() #summary of the datatypes in the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        10000 non-null  int64
 1   CustomerID           10000 non-null  int64
 2   ProductID            10000 non-null  int64
 3   ScarcityMessage      10000 non-null  bool
 4   CountdownTimer       10000 non-null  bool
 5   RecommendedLabel     10000 non-null  bool
 6   InfluencerCampaign   10000 non-null  bool
 7   FreeShipping         10000 non-null  bool
 8   TrendingBadge        10000 non-null  bool
 9   Purchased            10000 non-null  int64
 10  Quantity             10000 non-null  int64
 11  FinalAmount          10000 non-null  float64
 12  DecisionTimeMinutes  10000 non-null  float64
dtypes: bool(6), float64(2), int64(5)
memory usage: 605.6 KB

In [21]:
transactions.isnull().sum() #checking for nulls

TransactionID          0
CustomerID             0
ProductID              0
ScarcityMessage        0
CountdownTimer         0
RecommendedLabel       0
InfluencerCampaign     0
FreeShipping           0
TrendingBadge          0
Purchased              0
Quantity               0
FinalAmount            0
DecisionTimeMinutes    0
dtype: int64

In [22]:
transactions.duplicated().sum() #checking for duplicates

np.int64(0)

In [23]:
def age_group(age): #feature engineering customer age group
    if age <= 25:
        return 'Gen Z'
    elif age <= 35:
        return 'Young Adult'
    elif age <= 45:
        return 'Mid Career'
    elif age <= 55:
        return 'Mature Adults'
    else:
        return 'Seniors'

customers['Age_Group'] = customers['Age'].apply(age_group)
customers['Age_Group'].value_counts().sort_values(ascending=False)

Age_Group
Mid Career       322
Seniors          320
Mature Adults    311
Young Adult      303
Gen Z            244
Name: count, dtype: int64

In [24]:
def year_customer_range(years): #feature engineering years_customer_range
    if years == 0:
        return 'New Customer'
    elif years <= 2:
        return '1-2 Years'
    elif years <=5:
        return '3-5 Years'
    elif years <=10:
        return '6-10 Years'
    else:
        return '10+ Years'

customers['Years_As_Customer_Range'] = customers['YearsAsCustomer'].apply(year_customer_range)
customers['Years_As_Customer_Range'].value_counts().sort_values(ascending=False)

Years_As_Customer_Range
New Customer    845
6-10 Years      319
3-5 Years       202
1-2 Years       134
Name: count, dtype: int64

In [26]:
products['Discount_Percentage'] = ( #creating new column Discount %
    (products['OriginalPrice'] - products['CurrentPrice'])
    / products['OriginalPrice']) * 100

products['Discount_Percentage'] = products['Discount_Percentage'].round(2)
products['Discount_Percentage']

0      40.0
1      10.0
2       5.0
3      20.0
4      15.0
       ...
295     0.0
296    20.0
297    30.0
298    30.0
299    20.0
Name: Discount_Percentage, Length: 300, dtype: float64

In [27]:
def decision_time_range(time): #feature engineering a decision_time_range column
    if time < 10:
        return 'Fast'
    elif time < 25:
        return 'Medium'
    else:
        return 'Slow'

transactions['Decision_Speed'] = transactions['DecisionTimeMinutes'].apply(decision_time_range)

transactions['Decision_Speed'].value_counts().sort_values(ascending=False)

Decision_Speed
Medium    5538
Fast      3819
Slow       643
Name: count, dtype: int64

In [28]:
merged_data = pd.merge(transactions, customers, on='CustomerID', how='left') #Merging all three datasets
merged_data = pd.merge(merged_data, products, on='ProductID', how='left')

merged_data.head()

,TransactionID,CustomerID,ProductID,ScarcityMessage,CountdownTimer,RecommendedLabel,InfluencerCampaign,FreeShipping,TrendingBadge,Purchased,...,BrandFamiliarity,Age_Group,Years_As_Customer_Range,Category,Brand,OriginalPrice,CurrentPrice,Rating,ReviewCount,Discount_Percentage
0,1,134,102,False,False,True,True,True,True,1,...,High,Seniors,6-10 Years,Fashion,Nike,11122,10565.9,4.7,4396,5.0
1,2,1161,66,True,False,False,True,True,False,1,...,Low,Young Adult,New Customer,Fashion,H&M,3271,2943.9,3.7,2623,10.0
2,3,982,157,False,True,False,True,True,True,0,...,Medium,Young Adult,New Customer,Home,Prestige,33451,33451.0,4.6,3964,0.0
3,4,659,199,True,False,True,False,False,False,0,...,Medium,Seniors,New Customer,Beauty,Lakme,23235,18588.0,3.6,4936,20.0
4,5,650,79,True,False,False,False,False,False,0,...,Low,Young Adult,6-10 Years,Fashion,H&M,25179,20143.2,5.0,3352,20.0

In [29]:
merged_data.columns

Index(['TransactionID', 'CustomerID', 'ProductID', 'ScarcityMessage',
       'CountdownTimer', 'RecommendedLabel', 'InfluencerCampaign',
       'FreeShipping', 'TrendingBadge', 'Purchased', 'Quantity', 'FinalAmount',
       'DecisionTimeMinutes', 'Decision_Speed', 'Age', 'Gender', 'City',
       'IncomeLevel', 'Occupation', 'LoyaltyMember', 'YearsAsCustomer',
       'BrandFamiliarity', 'Age_Group', 'Years_As_Customer_Range', 'Category',
       'Brand', 'OriginalPrice', 'CurrentPrice', 'Rating', 'ReviewCount',
       'Discount_Percentage'],
      dtype='object')

In [30]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionID            10000 non-null  int64
 1   CustomerID               10000 non-null  int64
 2   ProductID                10000 non-null  int64
 3   ScarcityMessage          10000 non-null  bool
 4   CountdownTimer           10000 non-null  bool
 5   RecommendedLabel         10000 non-null  bool
 6   InfluencerCampaign       10000 non-null  bool
 7   FreeShipping             10000 non-null  bool
 8   TrendingBadge            10000 non-null  bool
 9   Purchased                10000 non-null  int64
 10  Quantity                 10000 non-null  int64
 11  FinalAmount              10000 non-null  float64
 12  DecisionTimeMinutes      10000 non-null  float64
 13  Decision_Speed           10000 non-null  object
 14  Age                      10000 non-null  int64
 15  Gender                   10000 non-null  object
 16  City                     10000 non-null  object
 17  IncomeLevel              10000 non-null  object
 18  Occupation               10000 non-null  object
 19  LoyaltyMember            10000 non-null  object
 20  YearsAsCustomer          10000 non-null  int64
 21  BrandFamiliarity         10000 non-null  object
 22  Age_Group                10000 non-null  object
 23  Years_As_Customer_Range  10000 non-null  object
 24  Category                 10000 non-null  object
 25  Brand                    10000 non-null  object
 26  OriginalPrice            10000 non-null  int64
 27  CurrentPrice             10000 non-null  float64
 28  Rating                   10000 non-null  float64
 29  ReviewCount              10000 non-null  int64
 30  Discount_Percentage      10000 non-null  float64
dtypes: bool(6), float64(5), int64(9), object(11)
memory usage: 2.0+ MB

In [31]:
merged_data.to_csv("consumer_behavior_master.csv", index=False)

In [32]:
merged_data.groupby('Age_Group')['Purchased'].mean() * 100 #Average purchase trends by age groups

Age_Group
Gen Z            66.933498
Mature Adults    68.588178
Mid Career       69.729730
Seniors          69.180633
Young Adult      70.015298
Name: Purchased, dtype: float64

In [33]:
merged_data.groupby('Gender')['Purchased'].mean() * 100 #Average purchase trends by gender

Gender
Female    68.730222
Male      69.235437
Name: Purchased, dtype: float64

In [34]:
merged_data['Years_As_Customer_Range'].value_counts()

Years_As_Customer_Range
New Customer    5592
6-10 Years      2187
3-5 Years       1332
1-2 Years        889
Name: count, dtype: int64

In [35]:
merged_data.groupby('Years_As_Customer_Range')['Purchased'].mean() * 100 #Purchase trends by customers in diff ranges

Years_As_Customer_Range
1-2 Years       75.815523
3-5 Years       77.102102
6-10 Years      75.537266
New Customer    63.394134
Name: Purchased, dtype: float64

In [36]:
merged_data.groupby('Category')['Purchased'].mean() * 100 #Purchase trends by category

Category
Beauty         70.421156
Books          69.019201
Electronics    67.061728
Fashion        68.811395
Home           69.593909
Name: Purchased, dtype: float64

In [37]:
merged_data.groupby('Discount_Percentage')['Purchased'].mean() * 100 #Purchase trends by disc percentages

Discount_Percentage
0.0     64.242424
5.0     64.900662
10.0    64.626391
15.0    66.955893
20.0    68.262295
25.0    75.144509
30.0    76.197605
40.0    71.777003
Name: Purchased, dtype: float64

In [38]:
merged_data.groupby("BrandFamiliarity")["Purchased"].mean() * 100 #How much brand familiarity affects purchase rates

BrandFamiliarity
High      76.773927
Low       62.762181
Medium    69.064105
Name: Purchased, dtype: float64

In [39]:
merged_data.groupby('ScarcityMessage')['Purchased'].mean() * 100 #How much scarcity msg increase purchase rates

ScarcityMessage
False    59.466282
True     80.826224
Name: Purchased, dtype: float64

In [40]:
merged_data.groupby('CountdownTimer')['Purchased'].mean() * 100 #How much urgency increase purchases

CountdownTimer
False    63.803073
True     76.919179
Name: Purchased, dtype: float64

In [41]:
merged_data.groupby('RecommendedLabel')['Purchased'].mean() * 100 #How much personal recommendations affect purchase rates

RecommendedLabel
False    63.348596
True     74.663452
Name: Purchased, dtype: float64

In [42]:
merged_data.groupby('InfluencerCampaign')['Purchased'].mean() * 100 #How much influencer campaign affect purchase rates

InfluencerCampaign
False    65.902841
True     74.811812
Name: Purchased, dtype: float64

In [43]:
merged_data.groupby("TrendingBadge")["Purchased"].mean() * 100 #How much trending and bandwagon effect contribute to purchase rates

TrendingBadge
False    62.348648
True     79.048099
Name: Purchased, dtype: float64

In [44]:
merged_data.groupby('Decision_Speed')['Purchased'].mean() * 100 #Which decision speeds lead to greater purchases

Decision_Speed
Fast      92.537313
Medium    57.313109
Slow      29.548989
Name: Purchased, dtype: float64

In [58]:
merged_data.groupby('FreeShipping')['FinalAmount'].mean() #Correlation between free shipping and spending amounts

FreeShipping
False    24876.638850
True     30370.192403
Name: FinalAmount, dtype: float64

In [57]:
merged_data.groupby('Category')['FinalAmount'].mean().sort_values(ascending=False) 
#Which categories generate the highest average order value

Category
Home           29399.618426
Books          28716.894240
Beauty         28193.737120
Electronics    27340.531654
Fashion        24530.638998
Name: FinalAmount, dtype: float64

In [54]:
merged_data.groupby(['ScarcityMessage', 'CountdownTimer'])['Purchased'].mean() * 100
#Combined effect of scarcity messages and countdown timers on purchase rates

ScarcityMessage  CountdownTimer
False            False             53.164179
                 True              69.080146
True             False             76.988531
                 True              86.750428
Name: Purchased, dtype: float64

In [55]:
merged_data.groupby(['Age_Group','ScarcityMessage'])['Purchased'].mean() * 100
#Which age groups are the most influenced by scarcity messages

Age_Group      ScarcityMessage
Gen Z          False              57.934783
               True               78.693182
Mature Adults  False              58.802817
               True               80.790340
Mid Career     False              59.348915
               True               81.898239
Seniors        False              59.006734
               True               81.770833
Young Adult    False              62.047101
               True               80.280047
Name: Purchased, dtype: float64

In [50]:
merged_data.groupby(['ScarcityMessage','CountdownTimer'])['Purchased'].mean() * 100
#How much urgency messages influence purchase rates

ScarcityMessage  CountdownTimer
False            False             53.164179
                 True              69.080146
True             False             76.988531
                 True              86.750428
Name: Purchased, dtype: float64

In [48]:
merged_data.groupby(['LoyaltyMember','FreeShipping'])['Purchased'].mean() * 100 #How much free shipping affects loyal customers

LoyaltyMember  FreeShipping
No             False           54.203306
               True            72.899236
Yes            False           70.252874
               True            81.728616
Name: Purchased, dtype: float64

In [49]:
merged_data.groupby(['Category','TrendingBadge'])['Purchased'].mean() * 100 #Which categories benefit the most from trending badges

Category     TrendingBadge
Beauty       False            63.477537
             True             80.357143
Books        False            62.997460
             True             78.552279
Electronics  False            59.265442
             True             78.355502
Fashion      False            62.012987
             True             79.228856
Home         False            63.980263
             True             78.647215
Name: Purchased, dtype: float64

In [52]:
merged_data.groupby(['InfluencerCampaign','BrandFamiliarity'])['Purchased'].mean() * 100
#What kind of brands benefit the most from influencers

InfluencerCampaign  BrandFamiliarity
False               High                73.099042
                    Low                 59.115479
                    Medium              66.768500
True                High                83.469150
                    Low                 69.736842
                    Medium              73.481385
Name: Purchased, dtype: float64